package com.slug.lifecycle;
/** 
* 1. 기능 : LifecyclEvent를 수신하여 비즈니스 로직을 처리하기 위한 Listener 인터페이스
* 2. 처리 개요 : LifecycleEvent를 수신하기 위한 Listener 인터페이스를 정의한다.
*      - Interface defining a listener for significant events (including "component
*        start" and "component stop" generated by a component that implements the
*        Lifecycle interface.
* 3. 주의사항 
*
* @author  : 
* @version : v 1.0.0
* @see : 관련 기능을 참조
* @since   : 
* @deprecated : 
*/


import java.util.EventObject;



public interface LifecycleListener {


    /** 
    * 1. 기능 :  LifecycleEvent 발생 시 실행된느 메서드
    * 2. 처리 개요 : LifecycleEvent 발생 시 실행되는 메서드이다.
    *     - Acknowledge the occurrence of the specified event.
    * 3. 주의사항 
    *
    * @param event LifecycleEvent that has occurred
    **/
    public void lifecycleEvent(LifecycleEvent event);


}
